export interface Question {
  id: string;
  stem: string;
  options: string[];
  correct: number;
  explanation: string;
  wrongExplanations: string[];
  topic: string;
  system: string;
  difficulty: 1 | 2 | 3;
  boardRelevance: string;
}

export const QUESTION_BANK: Question[] = [
  {
    id: "q001",
    system: "Renal", topic: "Nephrotic Syndrome", difficulty: 3, boardRelevance: "step1",
    stem: "A 6-year-old boy presents with periorbital edema and frothy urine 2 weeks after an upper respiratory infection. Serum albumin is 1.6 g/dL, total cholesterol 340 mg/dL. Urinalysis shows 4+ protein. Renal biopsy shows normal light microscopy but foot process effacement on electron microscopy. What is the most appropriate initial treatment?",
    options: ["Cyclosporine", "Prednisone", "Mycophenolate mofetil", "Rituximab"],
    correct: 1,
    explanation: "Minimal Change Disease (MCD) is the most common cause of nephrotic syndrome in children. It responds to corticosteroids (prednisone) in 85–90% of cases. The hallmark is normal light microscopy with foot process effacement on EM — the podocyte is the site of injury from T-cell-mediated cytokine release.",
    wrongExplanations: ["Cyclosporine is used for steroid-resistant or steroid-dependent MCD, not first-line.", "Mycophenolate is second or third-line for difficult cases.", "Rituximab is reserved for refractory disease."],
  },
  {
    id: "q002",
    system: "Cardiology", topic: "Heart Failure", difficulty: 2, boardRelevance: "both",
    stem: "A 68-year-old man with ischemic cardiomyopathy (EF 30%) is started on metoprolol succinate. He asks why he is being given a 'heart medication that slows the heart down' when his heart is already weak. What is the best explanation?",
    options: [
      "Beta-blockers increase cardiac output by reducing afterload",
      "Chronic sympathetic activation is maladaptive; blocking it reduces remodeling and improves long-term EF",
      "Beta-blockers increase preload by retaining sodium",
      "They prevent arrhythmias and have no direct effect on EF",
    ],
    correct: 1,
    explanation: "In HFrEF, chronic sympathetic nervous system activation causes cardiac remodeling (hypertrophy, fibrosis, myocyte apoptosis) and further worsens function. Beta-blockers interrupt this maladaptive neurohormonal cascade. Counterintuitively, though they acutely depress contractility, long-term use improves EF (often by 5–10 points) and reduces mortality. This is why they must be started low and titrated slowly.",
    wrongExplanations: ["Beta-blockers don't reduce afterload significantly — ACEi/ARBs do.", "Beta-blockers don't cause sodium retention — mineralocorticoid antagonists affect this.", "While antiarrhythmic properties are beneficial, the survival benefit comes from reverse remodeling."],
  },
  {
    id: "q003",
    system: "Pulmonology", topic: "COPD", difficulty: 2, boardRelevance: "step2",
    stem: "A 72-year-old smoker presents with acute exacerbation of COPD: increased sputum, worsening dyspnea, change in sputum color. O2 saturation is 84% on room air. After starting treatment, a nurse asks how much supplemental oxygen to give. What is the target O2 saturation in a COPD patient?",
    options: ["98–100% (normalize completely)", "94–98% (as high as possible)", "88–92% (permissive hypoxemia)", "No supplemental O2 — will worsen hypercapnia"],
    correct: 2,
    explanation: "In COPD patients who are chronic CO2 retainers, over-oxygenation can worsen hypercapnia. The mechanism involves: (1) loss of hypoxic pulmonary vasoconstriction, (2) Haldane effect — oxyhemoglobin releases CO2 less efficiently, and (3) blunted hypoxic drive (less important than once thought). Target SpO2 88–92% provides adequate oxygenation while avoiding CO2 retention. Titrate carefully with continuous monitoring.",
    wrongExplanations: ["Targeting 98–100% can precipitate hypercapnic respiratory failure in CO2 retainers.", "94–98% is appropriate for most non-COPD patients.", "Withholding O2 from a hypoxic patient is dangerous — hypoxia itself is life-threatening."],
  },
  {
    id: "q004",
    system: "Cardiology", topic: "Aortic Dissection", difficulty: 3, boardRelevance: "step2",
    stem: "A 58-year-old hypertensive man presents with sudden-onset 'tearing' chest pain radiating to the back. BP is 185/110 in right arm and 150/90 in left arm. CXR shows widened mediastinum. What is the MOST IMPORTANT immediate pharmacologic intervention?",
    options: [
      "IV nitroglycerin to reduce preload",
      "IV morphine for pain control",
      "IV labetalol or esmolol to reduce heart rate and BP",
      "IV furosemide to reduce pulmonary congestion",
    ],
    correct: 2,
    explanation: "In aortic dissection, the primary goals are: (1) reduce heart rate to <60 bpm to decrease shear stress on the aortic wall, and (2) reduce SBP to <120 mmHg. Beta-blockers (labetalol, esmolol) achieve both simultaneously — they are the cornerstone of initial management. Vasodilators like nitroprusside may be added AFTER beta-blockade. Never give a vasodilator first — the reflex tachycardia increases aortic wall stress and can worsen the dissection.",
    wrongExplanations: ["Nitroglycerin reduces preload but causes reflex tachycardia — harmful without prior beta-blockade.", "Morphine is reasonable for analgesia but does not address the underlying pathophysiology.", "Furosemide is not indicated — this is not a volume overload problem."],
  },
  {
    id: "q005",
    system: "Neurology", topic: "Stroke", difficulty: 2, boardRelevance: "step2",
    stem: "A 71-year-old woman presents with sudden-onset right-sided weakness and aphasia. Onset was 2.5 hours ago. NIHSS score is 12. Non-contrast CT head shows no hemorrhage and no early ischemic changes. BP is 175/95 mmHg. What is the most appropriate next step?",
    options: [
      "Start IV tPA (alteplase) immediately",
      "Lower BP to <140/90 with IV labetalol before tPA",
      "Order MRI brain before deciding on treatment",
      "Administer aspirin 325 mg and admit for monitoring",
    ],
    correct: 0,
    explanation: "This patient meets criteria for IV tPA: ischemic stroke within 4.5 hours, no hemorrhage on CT, NIHSS documents neurological deficit. BP of 175/95 does NOT need to be lowered before tPA — the threshold for treatment is BP >185/110. Treat only if BP exceeds that threshold. Time is brain — 'door to needle' goal is ≤60 minutes. Do not delay for MRI in an eligible patient.",
    wrongExplanations: ["Lowering BP to <140/90 is NOT required and wastes precious time. Only treat if BP >185/110 mmHg.", "MRI is more sensitive than CT but takes longer. Don't delay tPA for MRI in eligible patients.", "Aspirin alone is appropriate if tPA is contraindicated, but this patient is an eligible candidate."],
  },
  {
    id: "q006",
    system: "Endocrine", topic: "DKA", difficulty: 3, boardRelevance: "both",
    stem: "A 24-year-old with Type 1 DM presents with nausea, vomiting, and abdominal pain. ABG: pH 7.22, pCO2 28, HCO3 11. Glucose 480 mg/dL. K+ is 5.8 mEq/L on initial labs. After starting insulin infusion and IV fluids, serum K+ drops to 3.1 mEq/L. What explains the initial hyperkalemia AND subsequent hypokalemia?",
    options: [
      "Initial hyperkalemia from dehydration; hypokalemia from insulin causing osmotic diuresis",
      "Initial hyperkalemia from acidosis driving K+ extracellularly; hypokalemia from insulin driving K+ into cells + urinary losses",
      "Initial hyperkalemia from renal failure; hypokalemia from vomiting",
      "Initial hyperkalemia is normal for age; hypokalemia from IV fluid dilution",
    ],
    correct: 1,
    explanation: "In DKA: (1) Acidosis causes K+ to shift OUT of cells (H+/K+ exchange) → hyperkalemia despite total body K+ depletion. (2) After insulin, K+ shifts BACK INTO cells (insulin activates Na/K ATPase) AND osmotic diuresis has caused urinary K+ losses → hypokalemia. Total body K+ is ALWAYS depleted in DKA — the initial hyperkalemia masks this. Always start K+ replacement before the lab shows hypokalemia if K+ <5.5 and urine output is adequate.",
    wrongExplanations: ["Osmotic diuresis causes K+ loss but insulin driving K+ into cells is the primary mechanism of the drop.", "Renal failure causes hyperkalemia, but DKA patients typically have preserved renal function initially.", "Initial hyperkalemia is NOT normal — it reflects the H+/K+ exchange of acidosis."],
  },
  {
    id: "q007",
    system: "Gastroenterology", topic: "Liver Disease", difficulty: 2, boardRelevance: "step1",
    stem: "A 52-year-old man with alcoholic cirrhosis presents with hematemesis. Upper endoscopy reveals large esophageal varices with active bleeding. After initial resuscitation, which medication should be started IMMEDIATELY — even before endoscopy?",
    options: ["IV pantoprazole (PPI)", "IV octreotide (somatostatin analog)", "IV propranolol (beta-blocker)", "Oral lactulose"],
    correct: 1,
    explanation: "Octreotide (somatostatin analog) causes splanchnic vasoconstriction, reducing portal pressure and decreasing variceal bleeding. It should be started as soon as variceal bleeding is suspected — BEFORE endoscopy. Ceftriaxone should also be started empirically (SBP prophylaxis in cirrhosis with GI bleed improves survival). PPIs are used for peptic ulcer bleeding, not varices. Propranolol is for long-term prophylaxis, not acute bleeding. Lactulose treats hepatic encephalopathy.",
    wrongExplanations: ["PPIs reduce acid but have no effect on portal pressure or variceal bleeding.", "Propranolol is for prophylaxis (primary and secondary), not acute variceal hemorrhage.", "Lactulose treats hepatic encephalopathy and has no role in active bleeding."],
  },
  {
    id: "q008",
    system: "Hematology", topic: "Anemia", difficulty: 2, boardRelevance: "step1",
    stem: "A 35-year-old woman presents with fatigue for 3 months. CBC shows: Hgb 9.2 g/dL, MCV 72 fL, RDW 18. Serum ferritin is 6 ng/mL, serum iron is low, TIBC is elevated. What is the most likely diagnosis?",
    options: ["Anemia of chronic disease", "Iron deficiency anemia", "Beta-thalassemia trait", "Sideroblastic anemia"],
    correct: 1,
    explanation: "Iron deficiency anemia: microcytic (MCV 72), elevated RDW (reflects anisocytosis from mixed populations as iron depletes), low ferritin (best marker of iron stores), low serum iron, high TIBC (upregulated to capture scarce iron). This pattern — low ferritin, low iron, HIGH TIBC — is the classic iron deficiency triad. Anemia of chronic disease has low/normal TIBC and normal/high ferritin. Thalassemia has low RDW and normal ferritin.",
    wrongExplanations: ["Anemia of chronic disease has HIGH ferritin (acute phase reactant) and LOW/NORMAL TIBC.", "Beta-thalassemia trait has NORMAL ferritin, NORMAL TIBC, and LOW RDW — target cells on smear.", "Sideroblastic anemia has HIGH ferritin and HIGH serum iron."],
  },
  {
    id: "q009",
    system: "Infectious Disease", topic: "Sepsis", difficulty: 3, boardRelevance: "step2",
    stem: "A 67-year-old nursing home patient presents with fever, altered mental status, BP 85/55 mmHg, HR 128, RR 24, lactate 4.2 mmol/L. What is the correct sequence of the Surviving Sepsis Campaign 'Hour-1 Bundle'?",
    options: [
      "Culture → antibiotics → fluids → pressors → lactate",
      "Lactate → cultures → antibiotics → 30 mL/kg crystalloid → vasopressors if needed",
      "Antibiotics → cultures → fluids → lactate in 6 hours",
      "Fluids → pressors → antibiotics → culture within 24 hours",
    ],
    correct: 1,
    explanation: "Surviving Sepsis Campaign Hour-1 Bundle: (1) Measure lactate — guides severity and resuscitation goals. (2) Draw blood cultures BEFORE antibiotics (2 sets peripheral + central if line present). (3) Broad-spectrum antibiotics WITHIN 1 HOUR — this is the most time-sensitive intervention. (4) 30 mL/kg IV crystalloid for hypotension or lactate ≥4. (5) Vasopressors (norepinephrine first-line) if MAP <65 despite fluids. Mortality increases ~7% for each hour antibiotic delay.",
    wrongExplanations: ["Culture before antibiotics is correct, but antibiotics must follow immediately — within 1 hour total.", "You can't wait 6 hours for lactate or antibiotics — this is the original Sepsis-2 bundle, now outdated.", "Fluids first delays antibiotics — most critical intervention is antibiotics within the first hour."],
  },
  {
    id: "q010",
    system: "Renal", topic: "Acid-Base", difficulty: 3, boardRelevance: "step1",
    stem: "ABG: pH 7.28, pCO2 55 mmHg, HCO3 24 mEq/L. What is the primary disorder and is there adequate compensation?",
    options: [
      "Metabolic acidosis with respiratory compensation — adequate",
      "Respiratory acidosis (acute) — no compensation yet",
      "Respiratory acidosis (chronic) — adequate compensation",
      "Mixed respiratory acidosis and metabolic alkalosis",
    ],
    correct: 1,
    explanation: "Step 1: pH 7.28 = ACIDOSIS. Step 2: pCO2 55 = ELEVATED → primary RESPIRATORY ACIDOSIS. Step 3: Is compensation adequate? For ACUTE respiratory acidosis, HCO3 rises 1 mEq/L per 10 mmHg rise in CO2. Expected HCO3 = 24 + (55-40)/10 × 1 = 24 + 1.5 ≈ 25.5. Actual HCO3 is 24 — essentially no compensation. This is ACUTE. In CHRONIC respiratory acidosis, kidneys compensate 3.5 mEq/L per 10 mmHg CO2 rise over 3–5 days.",
    wrongExplanations: ["HCO3 24 is normal — this is not metabolic acidosis compensation.", "Correct — this is acute respiratory acidosis with minimal/no compensation.", "In chronic respiratory acidosis, HCO3 would be ~29.25 — this patient's HCO3 is too low for chronic."],
  },
  {
    id: "q011",
    system: "Cardiology", topic: "Atrial Fibrillation", difficulty: 2, boardRelevance: "step2",
    stem: "A 72-year-old man is found to have new-onset atrial fibrillation on EKG during a routine visit. He is hemodynamically stable with a heart rate of 95 bpm. He has hypertension and diabetes. No prior stroke. What is his CHA2DS2-VASc score and what does it indicate?",
    options: [
      "Score 2 — anticoagulation not recommended",
      "Score 3 — anticoagulation recommended",
      "Score 4 — anticoagulation strongly recommended",
      "Score 1 — anticoagulation optional",
    ],
    correct: 2,
    explanation: "CHA2DS2-VASc: C-Congestive HF(1) + H-Hypertension(1) + A2-Age≥75(2) + D-Diabetes(1) + S2-Stroke/TIA(2) + V-Vascular disease(1) + A-Age 65-74(1) + Sc-Sex category female(1). This patient: Age 72 (A=1 point) + Hypertension (H=1) + Diabetes (D=1) = Score 3. Anticoagulation is recommended for score ≥2 in men (≥3 in women). Use DOACs (apixaban, rivaroxaban) over warfarin for non-valvular AFib.",
    wrongExplanations: ["Score 2 would still indicate anticoagulation recommendation.", "Score 3 is correct — recommendation is 'strongly recommended' at this level.", "Score 1 would mean anticoagulation is optional; this patient scores higher."],
  },
  {
    id: "q012",
    system: "Pulmonology", topic: "Pulmonary Embolism", difficulty: 2, boardRelevance: "step2",
    stem: "A 45-year-old woman 10 days post-cesarean section presents with sudden shortness of breath and pleuritic chest pain. HR 118, RR 22, O2 sat 91%. Wells score is 6 (high probability). What is the most appropriate immediate next step?",
    options: [
      "D-dimer to rule out PE",
      "Start empiric anticoagulation then CT-PA",
      "Echocardiogram to assess RV strain",
      "V/Q scan (avoid CT due to radiation in post-partum woman)",
    ],
    correct: 1,
    explanation: "High pre-test probability (Wells ≥5) — skip D-dimer (it will be positive in post-surgical patients anyway and doesn't help clinically). Start therapeutic anticoagulation empirically IF no contraindication, THEN confirm with CT pulmonary angiography (gold standard). In post-partum women, the benefit of diagnosing/treating PE far outweighs radiation risk. V/Q scan is an alternative in true iodine allergy or severe renal disease, but CT-PA is preferred when possible.",
    wrongExplanations: ["D-dimer has no role in high-probability patients — recent surgery makes it unreliably elevated.", "Empiric anticoagulation + CT-PA is correct — this is the evidence-based approach.", "Echo can show RV strain supporting PE diagnosis but isn't diagnostic and delays treatment.", "CT-PA is preferred over V/Q when available — radiation risk is justified given clinical urgency."],
  },
  {
    id: "q013",
    system: "Endocrine", topic: "Thyroid", difficulty: 2, boardRelevance: "step1",
    stem: "A 28-year-old woman presents with 3 months of fatigue, weight gain (12 lbs), constipation, cold intolerance, and dry skin. TSH is 42 mIU/L, free T4 is 0.4 ng/dL. What is the most appropriate treatment?",
    options: [
      "Methimazole (antithyroid drug)",
      "Radioactive iodine ablation",
      "Levothyroxine (synthetic T4)",
      "Liothyronine (synthetic T3)",
    ],
    correct: 2,
    explanation: "Primary hypothyroidism (↑TSH, ↓free T4) is treated with levothyroxine (synthetic T4). The peripheral tissues convert T4 → T3 as needed, providing stable hormone levels. Methimazole and RAI are for HYPERTHYROIDISM. Liothyronine (T3) has a short half-life and is used primarily in myxedema coma or to optimize T3 levels in patients already on levothyroxine who remain symptomatic. TSH is the best monitoring parameter — target normal range.",
    wrongExplanations: ["Methimazole blocks thyroid hormone synthesis — used for Graves disease (hyperthyroidism).", "RAI destroys thyroid tissue — used for hyperthyroidism, would worsen hypothyroidism.", "Liothyronine is not first-line — its short half-life causes hormonal fluctuations."],
  },
  {
    id: "q014",
    system: "Neurology", topic: "Meningitis", difficulty: 3, boardRelevance: "step2",
    stem: "A 20-year-old college student presents with 12-hour history of fever, severe headache, neck stiffness, and non-blanching petechial rash. What is the most important immediate intervention?",
    options: [
      "CT head then LP for CSF culture, then antibiotics",
      "LP immediately for CSF culture, then antibiotics",
      "IV ceftriaxone + dexamethasone IMMEDIATELY — do not delay for imaging or LP",
      "Blood cultures, then LP, then antibiotics if LP confirms bacterial",
    ],
    correct: 2,
    explanation: "Non-blanching petechial rash + meningismus in a young adult = Neisseria meningitidis until proven otherwise. This is a MEDICAL EMERGENCY. Start IV ceftriaxone + dexamethasone (reduces inflammation, lowers hearing loss risk) IMMEDIATELY — do not wait for CT or LP. Every hour of delay increases mortality. Draw blood cultures BEFORE antibiotics if it takes <5 minutes. If papilledema or focal deficits are present, get CT before LP. But never delay antibiotics for imaging.",
    wrongExplanations: ["CT before antibiotics is appropriate only if there are signs of elevated ICP — but NEVER delay antibiotics.", "LP first delays antibiotics — in bacterial meningitis, each hour of delay increases mortality.", "The diagnosis is clinical — waiting for LP confirmation wastes life-saving time."],
  },
  {
    id: "q015",
    system: "Pharmacology", topic: "Drug Interactions", difficulty: 3, boardRelevance: "both",
    stem: "A 68-year-old man with AFib (on warfarin, INR 2.8) develops a UTI and is started on trimethoprim-sulfamethoxazole (TMP-SMX). Three days later his INR is 6.2 and he has gingival bleeding. What best explains this interaction?",
    options: [
      "TMP-SMX increases warfarin absorption in the gut",
      "TMP-SMX inhibits CYP2C9, reducing warfarin metabolism and increasing its effect",
      "TMP-SMX causes vitamin K deficiency by killing gut bacteria",
      "TMP-SMX displaces warfarin from protein binding sites",
    ],
    correct: 1,
    explanation: "Warfarin is primarily metabolized by CYP2C9. TMP-SMX (specifically sulfamethoxazole) is a CYP2C9 inhibitor — it reduces warfarin clearance, leading to drug accumulation and dramatically elevated INR. This is one of the most important drug interactions in clinical medicine. Always check for CYP2C9 inhibitors when prescribing to warfarin patients. Other CYP2C9 inhibitors: fluconazole, amiodarone, metronidazole. DOACs have fewer interactions but are not immune.",
    wrongExplanations: ["Absorption is not significantly altered by TMP-SMX.", "Killing gut bacteria reduces vitamin K production, a minor contributor — CYP inhibition is primary.", "Protein binding displacement is a minor mechanism; CYP inhibition is clinically dominant here."],
  },
  {
    id: "q016",
    system: "Cardiology", topic: "STEMI", difficulty: 2, boardRelevance: "step2",
    stem: "A 55-year-old man calls 911 for chest pain, diaphoresis, and nausea for 45 minutes. EMS finds ST elevations in leads II, III, aVF. He is brought to a PCI-capable hospital. What is the target door-to-balloon (D2B) time and preferred reperfusion strategy?",
    options: [
      "IV tPA within 30 minutes; PCI only if tPA fails",
      "Primary PCI within 90 minutes — preferred if D2B ≤90 min",
      "PCI within 90 minutes; if not available, transfer to PCI center within 12 hours",
      "Aspirin + heparin, then elective cath within 24–48 hours",
    ],
    correct: 1,
    explanation: "For STEMI at a PCI-capable center: primary PCI is preferred with a door-to-balloon goal ≤90 minutes. PCI is superior to fibrinolysis for restoring flow and reducing reinfarction. Give dual antiplatelet therapy (aspirin + P2Y12 inhibitor like ticagrelor) immediately. Heparin or bivalirudin as anticoagulation. Inferior STEMI (II, III, aVF) — always get right-sided EKG to rule out RV infarction before nitrates (contraindicated in RV MI).",
    wrongExplanations: ["Fibrinolysis is second-line — only use if PCI will be delayed >120 minutes from first medical contact.", "If D2B >120 min, fibrinolysis within 30 min ('door to needle') is preferred, not just 'transfer.'", "Elective cath is for NSTEMI/unstable angina — STEMI requires immediate reperfusion."],
  },
  {
    id: "q017",
    system: "Renal", topic: "AKI", difficulty: 2, boardRelevance: "step2",
    stem: "A 78-year-old woman with CKD (baseline Cr 1.4) undergoes coronary angiography. 72 hours later Cr rises to 2.8. UA shows granular casts, no protein, no blood. What is the diagnosis, and what is the most important preventive measure for next time?",
    options: [
      "Pre-renal AKI; IV fluids after procedure",
      "Contrast-induced nephropathy (CIN); pre-hydration with isotonic saline",
      "Atheroembolic renal disease; anticoagulation",
      "Post-renal obstruction; Foley catheter",
    ],
    correct: 1,
    explanation: "Contrast-induced nephropathy (CIN): Cr rises 48–72 hours post-contrast, peaks at day 3–5, usually returns to baseline in 7–10 days. Granular ('muddy brown') casts from tubular injury. Prevention: (1) Pre- and post-procedure IV isotonic saline (1 mL/kg/hr, starting 3–12h before). (2) Minimize contrast volume — use lowest dose possible. (3) Hold nephrotoxins (NSAIDs, metformin). N-acetylcysteine was once popular but evidence is weak. Atheroembolic disease has eosinophilia, livedo reticularis, subacute onset.",
    wrongExplanations: ["Pre-renal AKI has FENa <1% and responds to fluids quickly — granular casts indicate tubular injury (intrinsic).", "CIN with pre-hydration is correct — this is the standard of care.", "Atheroembolic disease occurs weeks after angiography with eosinophilia and skin findings.", "No signs of obstruction — post-renal would show hydronephrosis on ultrasound."],
  },
  {
    id: "q018",
    system: "Hematology", topic: "Coagulation", difficulty: 3, boardRelevance: "step1",
    stem: "A 45-year-old man is found to have an isolated elevated PTT. PT/INR is normal. He has no history of bleeding. Which diagnosis should be considered first and what confirmatory test would you order?",
    options: [
      "Hemophilia A (Factor VIII deficiency) — confirm with Factor VIII level",
      "Lupus anticoagulant — confirm with mixing study and DRVVT",
      "Von Willebrand disease — confirm with vWF antigen and activity",
      "Factor XII deficiency — no treatment needed",
    ],
    correct: 1,
    explanation: "Isolated elevated PTT with NO CLINICAL BLEEDING in an asymptomatic patient is the classic presentation of lupus anticoagulant (LA). LA is an antiphospholipid antibody that prolongs PTT in vitro but causes thrombosis in vivo (paradox). Confirmatory testing: PTT mixing study (doesn't correct — inhibitor present, not factor deficiency), then DRVVT (dilute Russell's viper venom time) which is sensitive/specific for LA. Hemophilia causes bleeding with isolated elevated PTT — but this patient has no bleeding history.",
    wrongExplanations: ["Hemophilia A causes elevated PTT with BLEEDING symptoms — this patient is asymptomatic.", "Lupus anticoagulant is correct — mixing study + DRVVT for confirmation.", "vWD can cause elevated PTT but also causes mucocutaneous bleeding — check history first.", "Factor XII deficiency also prolongs PTT without bleeding, but lupus anticoagulant is more clinically important to identify."],
  },
  {
    id: "q019",
    system: "Gastroenterology", topic: "IBD", difficulty: 2, boardRelevance: "step1",
    stem: "A 25-year-old man presents with 6 months of bloody diarrhea (6–8 stools/day), tenesmus, and urgency. Colonoscopy shows continuous mucosal inflammation from the rectum to the splenic flexure with no skip lesions. Biopsy shows crypt abscesses and goblet cell depletion. What is the diagnosis?",
    options: ["Crohn's disease", "Ulcerative colitis", "Infectious colitis from C. difficile", "Ischemic colitis"],
    correct: 1,
    explanation: "Ulcerative colitis: ALWAYS starts at the rectum and extends proximally in a CONTINUOUS pattern (no skip lesions). Mucosal layer only (unlike Crohn's which is transmural). Classic features: bloody diarrhea, tenesmus, rectal involvement always present. Biopsy: crypt abscesses + goblet cell depletion (mucus depletion from ongoing inflammation). Crohn's: skip lesions, transmural, can involve any part of GI tract, rectal sparing common, granulomas on biopsy. C. diff can mimic but check toxin assay.",
    wrongExplanations: ["Crohn's has SKIP lesions, transmural inflammation, and rectal sparing — opposite of this presentation.", "Ulcerative colitis is correct.", "C. diff causes diarrhea but not the described endoscopic/histologic pattern — check toxin assay.", "Ischemic colitis affects the 'watershed areas' (splenic flexure, sigmoid) — typically in older patients with vascular disease."],
  },
  {
    id: "q020",
    system: "Pharmacology", topic: "ACE Inhibitors", difficulty: 2, boardRelevance: "both",
    stem: "A 55-year-old man with hypertension and bilateral renal artery stenosis is prescribed lisinopril. Two weeks later, creatinine rises from 1.0 to 2.2 mg/dL. What is the mechanism of ACE inhibitor-induced AKI in this setting?",
    options: [
      "ACE inhibitors are directly nephrotoxic to the tubular epithelium",
      "ACE inhibitors dilate the efferent arteriole, reducing glomerular filtration pressure",
      "ACE inhibitors cause allergic interstitial nephritis",
      "ACE inhibitors increase renin, which vasoconstricts the glomerular arterioles",
    ],
    correct: 1,
    explanation: "In renal artery stenosis, the kidney relies on angiotensin II to maintain GFR by constricting the EFFERENT arteriole, which preserves glomerular filtration pressure despite reduced afferent flow. ACE inhibitors block angiotensin II formation → efferent arteriole DILATES → intraglomerular pressure drops dramatically → AKI. Bilateral RAS or unilateral with single functioning kidney are absolute contraindications to ACEi/ARBs. This is also seen in severe volume depletion, CHF, or cirrhosis where kidney is angiotensin II-dependent.",
    wrongExplanations: ["ACE inhibitors are not directly nephrotoxic — the mechanism is hemodynamic.", "Efferent dilation reducing GFR pressure is correct — this is the mechanism.", "ACE inhibitor-induced AIN (from captopril) is rare and not the mechanism here.", "ACE inhibitors REDUCE angiotensin II; they don't increase it."],
  },
  {
    id: "q021", system: "Neurology", topic: "Meningitis", difficulty: 3, boardRelevance: "step2",
    stem: "A 19-year-old college student presents with 12-hour history of fever, severe headache, nuchal rigidity, and a rapidly spreading non-blanching petechial rash. He is confused. What is the MOST IMPORTANT immediate intervention?",
    options: ["CT head then lumbar puncture", "IV ceftriaxone + dexamethasone immediately — do NOT delay for imaging", "Blood cultures × 2, then antibiotics", "LP for CSF analysis, then antibiotics if bacterial confirmed"],
    correct: 1,
    explanation: "Bacterial meningitis (likely N. meningitidis given petechial rash) carries 1-2% mortality per hour of delay. Start IV ceftriaxone + dexamethasone IMMEDIATELY. Draw blood cultures only if it takes <5 min — never delay antibiotics for cultures or imaging. CT is needed only if papilledema or focal neuro deficits are present. The non-blanching petechial rash is pathognomonic for meningococcemia.",
    wrongExplanations: ["CT before antibiotics is only appropriate if signs of ↑ ICP — never delay antibiotics.", "Correct — treat immediately without delay.", "Blood cultures before antibiotics acceptable only if <5 minutes — never delay antibiotics significantly.", "Waiting for LP results to confirm bacterial cause wastes life-saving time."],
  },
  {
    id: "q022", system: "Gastroenterology", topic: "Acute Pancreatitis", difficulty: 2, boardRelevance: "both",
    stem: "A 45-year-old obese woman with gallstones presents with severe epigastric pain radiating to the back, nausea, vomiting, and lipase of 2,400 U/L. She drinks 2 glasses of wine nightly. What is the most appropriate initial management?",
    options: ["NPO, aggressive IV fluids (lactated Ringer's preferred), pain control", "Emergency cholecystectomy", "Endoscopic retrograde cholangiopancreatography (ERCP)", "Nasogastric tube decompression"],
    correct: 0,
    explanation: "Acute pancreatitis management: (1) Aggressive IV fluids — lactated Ringer's preferred (reduces SIRS vs. normal saline); 250-500 mL/h initially. (2) Pain control — IV opioids. (3) NPO or early enteral nutrition (if tolerated). Routine ERCP only if concurrent cholangitis or persistent CBD obstruction. Cholecystectomy before discharge to prevent recurrence of gallstone pancreatitis — but NOT emergently. No role for prophylactic antibiotics.",
    wrongExplanations: ["IV fluids, NPO, and analgesia is correct first-line management.", "Emergency cholecystectomy is not indicated in acute pancreatitis — wait until inflammation resolves.", "ERCP is only indicated with concurrent cholangitis or CBD stone — not routine.", "NG tube has no role in pancreatitis management."],
  },
  {
    id: "q023", system: "Endocrine", topic: "Adrenal Disorders", difficulty: 3, boardRelevance: "step1",
    stem: "A 38-year-old woman presents with hypertension, hypokalemia (K+ 2.9), muscle weakness, and polyuria. She takes no diuretics. Plasma aldosterone:renin ratio is markedly elevated (>30). CT abdomen shows a 1.8 cm left adrenal adenoma. What is the definitive treatment?",
    options: ["Spironolactone lifelong", "Left adrenalectomy (laparoscopic)", "Fludrocortisone replacement", "Bilateral adrenalectomy"],
    correct: 1,
    explanation: "Primary hyperaldosteronism (Conn syndrome): HTN + hypokalemia + ↑ aldosterone:renin ratio. Confirmed adenoma on CT confirmed by adrenal vein sampling (gold standard to exclude bilateral hyperplasia). Unilateral adenoma → laparoscopic adrenalectomy = definitive cure. Bilateral hyperplasia → spironolactone or eplerenone (medical, not surgical). After surgery, BP improves in most, hypokalemia resolves immediately.",
    wrongExplanations: ["Spironolactone is for bilateral hyperplasia (non-surgical) — not for unilateral adenoma that can be cured.", "Adrenalectomy for confirmed unilateral adenoma is correct.", "Fludrocortisone is a mineralocorticoid replacement — wrong direction.", "Bilateral adrenalectomy is excessive — only remove the side with the adenoma."],
  },
  {
    id: "q024", system: "Hematology", topic: "Antiphospholipid Syndrome", difficulty: 3, boardRelevance: "step1",
    stem: "A 35-year-old woman has 3 recurrent miscarriages, a DVT on OCPs, and livedo reticularis. PTT is prolonged; mixing study does not correct. What is the mechanism of the prolonged PTT and the paradox of this condition?",
    options: ["Factor VIII inhibitor — causes bleeding paradoxically", "Lupus anticoagulant (antiphospholipid Ab) — prolongs PTT in vitro but causes THROMBOSIS in vivo", "Factor V Leiden — prolongs PTT and causes thrombosis", "Heparin contamination — prolongs PTT, no clinical effect"],
    correct: 1,
    explanation: "Antiphospholipid syndrome (APS) paradox: lupus anticoagulant (LA) prolongs PTT in vitro because it binds phospholipids in the assay — BUT causes thrombosis in vivo by activating platelets and endothelium. Mixing study doesn't correct = inhibitor present. Triad: thrombosis (arterial or venous) + obstetric morbidity (recurrent miscarriage) + positive antiphospholipid antibodies. Treatment: warfarin (INR 2-3) for thrombosis; aspirin + heparin during pregnancy for obstetric APS.",
    wrongExplanations: ["Factor VIII inhibitor causes bleeding — this patient has thrombosis.", "APS with LA is the paradox described — correct.", "Factor V Leiden doesn't prolong PTT and mixing study corrects.", "Heparin contamination would be from an external source — not this clinical picture."],
  },
  {
    id: "q025", system: "Infectious Disease", topic: "Opportunistic Infections", difficulty: 2, boardRelevance: "step1",
    stem: "A 34-year-old man with HIV and CD4 count of 45 presents with progressive headache and fever for 3 weeks. CSF: ↑ opening pressure, lymphocytic pleocytosis, ↓ glucose, ↑ protein. India ink preparation shows encapsulated yeast. What is the first-line treatment?",
    options: ["Trimethoprim-sulfamethoxazole + steroids", "Amphotericin B liposomal + flucytosine × 2 weeks, then fluconazole", "Pyrimethamine + sulfadiazine", "Initiate HAART immediately"],
    correct: 1,
    explanation: "Cryptococcal meningitis: CD4 <200 (typically <100), India ink positive for encapsulated yeast, subacute meningitis, high opening pressure. Treatment phases: (1) Induction: liposomal amphotericin B + flucytosine × 2 weeks. (2) Consolidation: fluconazole 400mg/day × 8 weeks. (3) Maintenance: fluconazole 200mg/day indefinitely. High opening pressure → therapeutic LPs (reduce ICP, prevent blindness). Delay HAART 5 weeks to avoid IRIS.",
    wrongExplanations: ["TMP-SMX + steroids is for PCP (CD4 <200, bilateral interstitial infiltrates, ↑ LDH).", "Amphotericin B + flucytosine is correct induction therapy.", "Pyrimethamine + sulfadiazine is for CNS toxoplasmosis (ring-enhancing lesions, CD4 <100).", "HAART should be delayed 5 weeks after starting antifungals to prevent immune reconstitution inflammatory syndrome (IRIS)."],
  },
  {
    id: "q026", system: "Rheumatology", topic: "Lupus (SLE)", difficulty: 2, boardRelevance: "step1",
    stem: "A 26-year-old Black woman with SLE presents with proteinuria (3.2 g/day) and RBC casts on urinalysis. ANA 1:640, anti-dsDNA positive, low C3/C4. What does the urinalysis indicate and what is the next step?",
    options: ["UTI — urine culture and antibiotics", "Lupus nephritis — kidney biopsy to classify before starting treatment", "Preeclampsia — check blood pressure and admit", "IgA nephropathy — no immediate treatment"],
    correct: 1,
    explanation: "Lupus nephritis (LN): proteinuria + RBC casts = glomerulonephritis in SLE context. RBC casts are pathognomonic for glomerulonephritis. Kidney biopsy is essential — classifies LN by WHO/ISN (Class I-VI) and guides treatment. Class III/IV (proliferative LN): mycophenolate mofetil + high-dose steroids (± belimumab). Class V (membranous LN): mycophenolate or calcineurin inhibitors. Class VI (sclerotic): conservative. Without biopsy, you cannot know which treatment to give.",
    wrongExplanations: ["RBC casts are not from UTI — they indicate glomerular hemorrhage.", "Lupus nephritis requiring biopsy is correct.", "Preeclampsia is in pregnant patients — no mention of pregnancy.", "IgA nephropathy presents with gross hematuria after URI in young males — different picture."],
  },
  {
    id: "q027", system: "Cardiology", topic: "Pericardial Disease", difficulty: 2, boardRelevance: "step1",
    stem: "A 30-year-old man presents with sharp chest pain that worsens lying down and improves leaning forward. He had a URI 2 weeks ago. EKG shows diffuse saddle-shaped ST elevation and PR depression in all leads except aVR. Troponin mildly elevated. What is the first-line treatment?",
    options: ["Aspirin 750-1000 mg TID + colchicine 0.5 mg BID × 3 months", "Pericardiocentesis", "IV heparin and aspirin (treat as ACS)", "High-dose prednisone"],
    correct: 0,
    explanation: "Acute pericarditis: sharp positional pain (worse supine, better leaning forward = 'tripod position') + pericardial friction rub + diffuse saddle-shaped ST elevation + PR depression (most specific EKG finding). Mild troponin elevation from epicardial inflammation is common. First-line: NSAIDs (aspirin 750-1000 mg TID × 1-2 weeks) + colchicine (reduces recurrence rate by 50%). Restrict strenuous activity. Reserve steroids for NSAID failures — steroids increase recurrence risk.",
    wrongExplanations: ["Aspirin + colchicine is correct first-line.", "Pericardiocentesis is for cardiac tamponade (Beck's triad: hypotension, JVD, muffled heart sounds) — not small effusion.", "Heparin is contraindicated in pericarditis — risk of hemorrhagic effusion. Don't treat as ACS without clear evidence.", "Corticosteroids are third-line and increase recurrence — avoid early use."],
  },
  {
    id: "q028", system: "Gastroenterology", topic: "Inflammatory Bowel Disease", difficulty: 2, boardRelevance: "step1",
    stem: "A 26-year-old man with a 5-year history of Crohn's disease (skip lesions, terminal ileum) presents with worsening abdominal pain, fever, and a palpable RLQ mass. CT shows a 4 cm fluid collection adjacent to the terminal ileum with surrounding fat stranding. What is the most appropriate management?",
    options: ["High-dose prednisone", "CT-guided drainage + antibiotics, then elective surgery after 6-8 weeks", "Emergency surgery with primary anastomosis", "Infliximab (anti-TNF) immediately"],
    correct: 1,
    explanation: "Crohn's abscess: CT-guided percutaneous drainage is the bridge to definitive surgery. Drain the abscess, treat with antibiotics (ciprofloxacin + metronidazole), and allow inflammation to subside. Elective surgery (ileocecal resection) is then performed under controlled conditions with much lower complication rate. Do NOT give immunosuppressants (steroids, biologics) with an active abscess — infection will worsen. Emergency surgery is reserved for perforation, peritonitis, or failure of drainage.",
    wrongExplanations: ["Steroids in an active abscess are contraindicated — suppress immune response, worsen infection.", "CT-guided drainage then elective surgery is correct.", "Emergency surgery has higher complication rate than drain → wait → elective approach.", "Infliximab (anti-TNF) is contraindicated with active infection/abscess — can cause sepsis."],
  },
  {
    id: "q029", system: "Neurology", topic: "Seizures / Epilepsy", difficulty: 2, boardRelevance: "step2",
    stem: "A 35-year-old woman with epilepsy on valproic acid becomes pregnant. Her seizures have been well-controlled for 2 years. She asks about continuing valproic acid during pregnancy. What is your recommendation?",
    options: ["Continue valproic acid — seizure control is paramount", "Switch to levetiracetam or lamotrigine — valproic acid has highest teratogenic risk", "Discontinue all antiepileptics during first trimester", "Add folate but continue valproic acid unchanged"],
    correct: 1,
    explanation: "Valproic acid has the highest teratogenic risk of all antiepileptics: neural tube defects (spina bifida, 1-2%), cardiac defects, cleft palate, and cognitive/developmental delays (valproate embryopathy). FDA category D. Switch to lamotrigine or levetiracetam before conception if possible — lowest teratogenic risk. If switching during pregnancy, do so carefully to avoid breakthrough seizures (which are also dangerous). All women of childbearing age on antiepileptics should take high-dose folate (4 mg/day vs. 0.4 mg standard).",
    wrongExplanations: ["Valproic acid should be avoided in pregnancy due to high teratogenic risk — switch if possible.", "Switching to levetiracetam or lamotrigine is correct.", "Abruptly stopping antiepileptics risks status epilepticus — dangerous for mother and fetus.", "Adding folate is important but does not sufficiently mitigate valproate teratogenicity — switching is preferred."],
  },
  {
    id: "q030", system: "Pharmacology", topic: "Drug-Induced Toxicity", difficulty: 3, boardRelevance: "both",
    stem: "A 72-year-old man on amiodarone for 3 years for AFib presents with dyspnea. CXR shows bilateral interstitial infiltrates. PFTs show restrictive pattern with ↓ DLCO. Bronchoscopy BAL shows foamy macrophages. He also has blue-gray skin discoloration on sun-exposed areas. What is the diagnosis and management?",
    options: ["Heart failure exacerbation — increase diuretics", "Amiodarone pulmonary toxicity — stop amiodarone, systemic corticosteroids", "Community-acquired pneumonia — azithromycin", "Pulmonary fibrosis (IPF) — pirfenidone"],
    correct: 1,
    explanation: "Amiodarone toxicity: most feared complication is pulmonary toxicity (1-5% of patients, can be fatal). Occurs months to years after starting. Findings: bilateral interstitial infiltrates, restrictive PFTs, ↓ DLCO, BAL with foamy macrophages (phospholipid accumulation). The blue-gray skin discoloration (lipofuscin deposits) is pathognomonic. Management: STOP amiodarone immediately, start systemic corticosteroids. Monitor: baseline and annual PFTs, TFTs (hypothyroidism/hyperthyroidism), LFTs, eye exams, thyroid.",
    wrongExplanations: ["Heart failure causes pulmonary edema (alveolar pattern) not interstitial fibrosis — and skin discoloration wouldn't be from HF.", "Amiodarone pulmonary toxicity with drug cessation + steroids is correct.", "CAP doesn't cause skin discoloration or foamy macrophages on BAL.", "IPF is a diagnosis of exclusion — amiodarone exposure makes drug toxicity the primary diagnosis."],
  },
];
